input_zarr_zip: "/nfs/khan/trainees/dbansal7/extracted_data/sub-T20_sample-anterior_acq-MICA40x_stain-LFB_chunk-024_BF.ome.zarr/0"
zarr_level: 5
channel_index: 0
mask_nii: "/nfs/khan/trainees/mliu366/2_histo3D_reg/data/IHC_nii/sub-T20_ses-01_chunk-024_stain-LFB_mask.nii.gz"

out_dir: "results/level-5"

# Patch tiling
patch_height: 100
patch_width: 100
patch_overlap_y: 0
patch_overlap_x: 0
edge_mode: "drop"

# Structure tensor parameters
sigma_g: 2
sigma_w: 4
truncate: 7

# Histogram / peak parameters
bins: 64
AI_power: 1.0
AI_thresh: null
harmonic_M: 10
peak_distance: 3